name: OKEX Daily report everyday at 22:55 GMT+7

on:
  schedule:
    - cron: "45 15 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run daily report file
      run: |
        python send_summary.py --exchange okex
      env:
        TOKEN: ${{ secrets.BOT_TOKEN }}
        OKEX_CHAT_ID: ${{ secrets.OKEX_CHAT_ID }}
